export interface TCustomer {
  id: string;
  logo: string;
  image: string;
  text: string;
  stat1: number;
  stat1Prefix: string;
  stat1Suffix: string;
  stat1Label: string;
  stat1Description: string;
  stat2: number;
  stat2Prefix: string;
  stat2Suffix: string;
  stat2Label: string;
  stat2Description: string;
  wwaMaxWidth: number;
}

export const customers: TCustomer[] = [
  /* {
    id: "disney",
    logo: "images/clients/logos/disney.svg",
    image: "images/clients/preview/disney.webp",
    text: "At Disney, BetterUp helped operationalize the CHRO’s leadership framework across 40,000 managers, enabling consistent leadership behaviors that support creativity, innovation, and performance at global scale.",
    stat1: 99,
    stat1Prefix: "",
    stat1Suffix: "%",
    stat1Label: "of coaching sessions rated as valuable use of time",
    stat1Description: "",
    stat2: 40,
    stat2Prefix: "",
    stat2Suffix: "K",
    stat2Label: "Leaders getting personalized development",
    stat2Description: "",
    wwaMaxWidth: 124,
  }, */
  {
    id: "petronas",
    logo: "images/clients/logos/mercedes.svg",
    image: "images/clients/preview/mercedes.webp",
    text: "Mercedes-AMG Petronas Formula One uses BetterUp to build pressure-ready leaders—supporting elite performance across the organization, from headquarters to the pit.",
    stat1: 99,
    stat1Prefix: "",
    stat1Suffix: "%",
    stat1Label: "reported real improvements in daily performance",
    stat1Description: "",
    stat2: 21,
    stat2Prefix: "",
    stat2Suffix: "%",
    stat2Label: "productivity gains",
    stat2Description: "",
    wwaMaxWidth: 197,
  },
  {
    id: "novartis",
    logo: "images/clients/logos/novartis.svg",
    image: "images/clients/preview/novartis.webp",
    text: "With BetterUp, Novartis scaled leadership development enterprise-wide, driving leadership impact through human coaching and expanding AI coaching access to 65K employees during a major strategic shift.",
    stat1: 32,
    stat1Prefix: "+",
    stat1Suffix: "%",
    stat1Label: "Improvement IN Strategic Planning",
    stat1Description: "Strengthening leaders’ ability to translate strategy into execution.",
    stat2: 20,
    stat2Prefix: "+",
    stat2Suffix: "%",
    stat2Label: "Improvement IN focus",
    stat2Description: "Enabling managers to prioritize effectively and drive execution across teams.",
    wwaMaxWidth: 187,
  },
  {
    id: "usaf",
    logo: "images/clients/logos/usaf.svg",
    image: "images/clients/preview/usaf.webp",
    text: "BetterUp partners with the U.S. Air Force to prepare leaders for high-stakes missions, supporting retention of critical talent.",
    stat1: 10,
    stat1Prefix: "",
    stat1Suffix: "x",
    stat1Label: "increase in commitment",
    stat1Description: "",
    stat2: 16,
    stat2Prefix: "",
    stat2Suffix: "%",
    stat2Label: "increase in mission readiness",
    stat2Description: "",
    wwaMaxWidth: 98,
  },
  {
    id: "bp",
    logo: "images/clients/logos/bp.svg",
    image: "images/clients/preview/bp.webp",
    text: "As bp reset its strategy to sharpen focus and performance, BetterUp supported critical-talent leaders in building a stronger performance culture, improving decision-making and strategic thinking through significant change.",
    stat1: 22,
    stat1Prefix: "",
    stat1Suffix: "%",
    stat1Label: "Increase in Decision Making",
    stat1Description: "Enabling leaders to make timely, high-quality decisions by balancing insight, judgement, and accountability.",
    stat2: 23,
    stat2Prefix: "",
    stat2Suffix: "%",
    stat2Label: "increase in strategic thinking",
    stat2Description: "Strengthening leaders’ ability to anticipate trends, connect insights, and shape clear strategic direction.",
    wwaMaxWidth: 74,
  },
  {
    id: "unilever",
    logo: "images/clients/logos/unilever.svg",
    image: "images/clients/preview/unilever.webp",
    text: "At Unilever, BetterUp supported a multi-layered culture transformation, shifting four critical leadership behaviors to enable scaled innovation, improve market performance, and strengthen execution while enhancing organizational efficiency.",
    stat1: 23,
    stat1Prefix: "+",
    stat1Suffix: "%",
    stat1Label: "increase in strategic thinking",
    stat1Description: "Strengthening leaders’ ability to anticipate trends, connect insights, and shape clear strategic direction.",
    stat2: 18,
    stat2Prefix: "+",
    stat2Suffix: "%",
    stat2Label: "INCREASE IN goal attainment",
    stat2Description: "Strengthening leaders’ ability to set clear goals and consistently deliver on commitments.",
    wwaMaxWidth: 82,
  },
  {
    id: "salesforce",
    logo: "images/clients/logos/salesforce.svg",
    image: "images/clients/preview/salesforce.webp",
    text: "At Salesforce, BetterUp provides real-time organizational intelligence, helping leaders build resilience, adapt faster, and sustain performance across 76K employees as the company navigates AI-driven change.",
    stat1: 76,
    stat1Prefix: "",
    stat1Suffix: "K",
    stat1Label: "Employees with betterup",
    stat1Description: "",
    stat2: 8,
    stat2Prefix: "",
    stat2Suffix: "%",
    stat2Label: "Increase in productivity",
    stat2Description: "",
    wwaMaxWidth: 104,
  },
  {
    id: "blackrock",
    logo: "images/clients/logos/blackrock.svg",
    image: "images/clients/preview/blackrock.webp",
    text: "BlackRock trusts BetterUp to strengthen its talent strategy by equipping 1,200 managers with the skills to cultivate a culture that drives innovation, performance, and long-term success.",
    stat1: 10,
    stat1Prefix: "",
    stat1Suffix: "%",
    stat1Label: "lift in team performance",
    stat1Description: "",
    stat2: 39,
    stat2Prefix: "",
    stat2Suffix: "%",
    stat2Label: "reduction in top leadership turnover",
    stat2Description: "",
    wwaMaxWidth: 152,
  },
]
